### ISSUE TITLE
Can't run `npm` or `npx`: missing `node` in PATH

### ISSUE THREAD

**Issue by stephenwade** [kevgo/run-that-app#298]
When using rta to run `npm` or `npx`, I get the error "node: command not found".

Probably, apps that are installed via another app (like these two) should have the parent app in their PATH when run.

**Comment by kevgo** [comment]
Thanks for catching and reporting this bug! Honestly, it never crossed my mind to test this functionality without Node installed on my machine. 🤦‍♂️

The issue appears to be that run-that-app directly invokes the `npm` executable, but doesn’t ensure that the `node` executable is available in the subshell to actually execute it.

I've identified two potential fixes for this:

1. Adjust the `$PATH`: Modify the environment so that the `node` executable installed by run-that-app is included in the PATH before invoking `npm`.
2. Explicitly invoke Node: Keep the `$PATH` as is, but invoke `npm` using `node npm`, where both `node` and `npm` are the full paths to the executables installed by run-that-app.

**Comment by kevgo** [comment]
I agree that including the other executable in the PATH is the better solution. This approach supports a broader range of use cases. For example, it would handle scenarios where `npm` spawns a subshell that requires `node` to be available.

**Comment by kevgo** [comment]
Why not always include all relevant binaries in the PATH when running an executable? It doesn't hurt, and it's necessary in some situations (which are hard to predict).
